proyecto_django/bienvenido/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("chau/", views.chau, name="despedida"),
    path("base/", views.base_template),

    path("empleado/", views.listar_empleados, name="lista_empleados"),
    path("empleado/search/", views.search_empleados),    

    path("empleado/nuevo/", views.crear_empleado),
    path("empleado/<int:id>", views.mostrar_empleado, name="empleado"),
    path("empleado/<int:id>/borrar/", views.borrar_empleado, name="borrar_empleado"),
    path("empleado/<int:id>/editar/", views.editar_empleado, name="editar_empleado"),


    path("departamento/", views.listar_departamentos, name="lista_departamentos"),

    path("departamento/nuevo/", views.crear_departamento),
    path("departamento/<int:id>", views.mostrar_departamento, name="departamento"),
    path("departamento/<int:id>/borrar", views.borrar_departamento, name="borrar_departamento"),

]

proyecto_django/proyecto_django/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("empresa/", include("bienvenido.urls")),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL,
     document_root=settings.MEDIA_ROOT)

proyecto_django/bienvenido/models.py
from django.db import models

# Create your models here.
class Departamento(models.Model):
    nombre = models.CharField(max_length=30)
    descripcion = models.CharField(max_length=30)

    def cantidad_empleados(self):
        lista_emp = Empleado.objects.filter(departamento = self)
        return len(lista_emp)

    def __str__(self):
        return self.nombre


class Empleado(models.Model):
    nombre = models.CharField(max_length=30)
    nacimiento = models.DateField()
    sueldo = models.DecimalField(decimal_places=2, max_digits=10)
    departamento = models.ForeignKey(Departamento, on_delete = models.CASCADE)
    foto = models.ImageField(upload_to="empleados/", null=True, blank=True)
    def __str__(self):
        return self.nombre

proyecto_django/bienvenido/forms.py
from django import forms
from .models import Empleado
from .models import Departamento


class EmpleadoForm(forms.ModelForm):
    class Meta:
        model = Empleado
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(EmpleadoForm, self).__init__(*args, **kwargs)
        self.fields['nombre'].widget.attrs.update({'class' : 'texto-rojo','placeholder' : 'ingrese su nombre', 'type' : 'text'})

class DepartamentoForm(forms.ModelForm):
    class Meta:
        model=Departamento
        fields="__all__"

proyecto_django/bienvenido/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from bienvenido.models import Empleado, Departamento
from bienvenido.forms import EmpleadoForm, DepartamentoForm



def index(request):
    contexto = {
        "saludo":"Hola Mundo",
        "numero":234
    }
    return render(request, "bienvenido/index.html", contexto)
    #return HttpResponse("Hola Mundo!")

def chau(request):
    return render(request, "bienvenido/chau.html", {})

def base_template(request):
    return render(request, "base.html", {})



def listar_empleados(request):
    lista_empleados = Empleado.objects.all()
    contexto = {
        "empleados":lista_empleados,
    }
    return render(request, "bienvenido/empleado/empleados.html", contexto)


def search_empleados(request):
    print(request.GET)
    nombre = request.GET.get("nombre_empleado", "")

    lista_empleados = Empleado.objects.filter(nombre__icontains = nombre)
    contexto = {
        "empleados":lista_empleados,
        "param_nombre":nombre
    }
    return render(request, "bienvenido/empleado/search_empleados.html", contexto)


def crear_empleado(request):
    if request.method == "POST":
        form = EmpleadoForm(request.POST, request.FILES)
        if form.is_valid():
            empleado = form.save(commit=False)
            empleado.save()
            return HttpResponse("EMPLEADO CREADO")
        else:
            print(form.errors)

    form = EmpleadoForm()
    contexto = {"form":form,
        "operacion":"CREAR"
    }
    return render(request, "bienvenido/empleado/nuevo_empleado.html", contexto)


def mostrar_empleado(request, id):
    emp = Empleado.objects.get(pk=id)
    contexto = {
        "empleado":emp
    }
    return render(request, "bienvenido/empleado/empleado.html", contexto)
    #return HttpResponse(emp.nombre)


def borrar_empleado(request, id):
    emp = Empleado.objects.get(pk=id)
    nombre = emp.nombre
    emp.delete()
    return HttpResponse(nombre + " Borrado!")


def editar_empleado(request, id):
    empleado = Empleado.objects.get(pk = id)

    if request.method == "GET":
        form = EmpleadoForm(instance = empleado)
        contexto = {
            "form" : form
        }
        return render(request, "bienvenido/empleado/nuevo_empleado.html", contexto)

    elif request.method == "POST":
        form = EmpleadoForm(request.POST, instance = empleado)
        if form.is_valid():
            emp = form.save()
            return redirect("empleado", emp.id)



def listar_departamentos(request):
    departamentos = Departamento.objects.all()
    contexto = {
        "departamentos": departamentos,
    }
    return render(request, "bienvenido/departamento/lista_departamentos.html", contexto)


def crear_departamento(request):
    if request.method == "POST":
        form=DepartamentoForm(request.POST)
        if form.is_valid():
            Departamento=form.save()
            return redirect("departamentos_lista")
    form=DepartamentoForm()
    contexto={"form":form}
    return render(request, "bienvenido/departamento/nuevo_departamento.html", contexto)


def mostrar_departamento(request, id):
    depto = Departamento.objects.get(pk=id)
    contexto = {
        "departamento":depto
    }
    return render(request, "bienvenido/departamento/mostrar_departamento.html", contexto)


def borrar_departamento(request, id):
    dept= Departamento.objects.get(pk=id)
    dept.delete()
    return HttpResponse(dept.nombre,"Ya se borro!")    

proyecto_django/bienvenido/templates/bienvenido/chau.html
Adios

proyecto_django/bienvenido/templates/bienvenido/departamento/lista_departamentos.html
{%extends "base.html"%}

{%block titulo%}
    Lista Departamentos
{% endblock %}

{% block contenido%}
    {% for dpto in departamentos %}
        Nombre: {{ dpto.nombre }}<br>
        Descripción: {{ dpto.descripción }}<br>
        <a href="#">ver detalles</a><br>  
        <a href="#">Borrar</a>
        <br>
        <br>
    {% endfor %}
{% endblock%}

proyecto_django/bienvenido/templates/bienvenido/departamento/mostrar_departamento.html
{% extends "base.html" %}
{%block titulo%}
    Departamento: {{departamento.nombre}}
{% endblock %}

{% block contenido %}
    Departamento: {{ departamento.nombre }}<br>
    Descripción: {{ departamento.descripcion }}<br>
    Cantidad de empleados: {{ departamento.cantidad_empleados }}<br>
    Cantidad de empleados: {{ departamento.empleado_set.count }}<br>
    Cantidad de empleados: {{ departamento.empleado_set.values }}<br>
    <br>

{% endblock %}

proyecto_django/bienvenido/templates/bienvenido/departamento/nuevo_departamento.html
{%extends "base.html"%}

{% block titulo%}
Nuevo Departamento
{% endblock %}<br>

{% block contenido%}
    <form method="POST">
        {%csrf_token%}
        {{form.as_p}}
        <button type="submit">Crear</button>
    </form>
{% endblock %}<br>

proyecto_django/bienvenido/templates/bienvenido/empleado/empleado.html
{% extends "base.html" %}
{%block titulo%}
    Empleado: {{empleado.nombre}}
{% endblock %}

{% block contenido %}
    <img src="{{empleado.foto.url }}"><br>

    Empleado: {{ empleado.nombre }}<br>
    Departamento: {{ empleado.departamento }}<br>
    Sueldo: ${{ empleado.sueldo }}

    {% if empleado.sueldo > 16000 %}
        :)
    {% else %}
        :(
    {% endif %}
    <br>
    <a href="{%url 'borrar_empleado' empleado.id%}">Borrar</a>
{% endblock %}

proyecto_django/bienvenido/templates/bienvenido/empleado/empleados.html
{% extends "base.html" %}
{% load static %}

{%block titulo%}
    Lista Empleados
{% endblock %}


{% block contenido %}
    <img src="{% static 'emp.jpg' %}"><br>
    
    {% for empleado in empleados %}
        Nombre: {{ empleado.nombre }}<br>
        Sueldo: {{ empleado.sueldo }}<br>
        {% if empleado.sueldo > 18000 %}
            Sueldo mayor a 18000 <br>
        {% endif %}
        <a href="{% url 'empleado' empleado.id %}">ver detalles</a><br>  
        <a href="{%url 'borrar_empleado' empleado.id%}">Borrar</a>
        <br>
        <br>
    {% endfor %}
{% endblock %}

proyecto_django/bienvenido/templates/bienvenido/empleado/nuevo_empleado.html
{% extends "base.html" %}

{%block titulo%}
    {% if operacion == 'CREAR' %}
        Nuevo Empleado
    {% else %}
        Editar Empleado
    {% endif %}
{% endblock %}<br>

{% block contenido %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
            {% if operacion == 'CREAR' %}
                Crear
            {% else %}
                Guardar
            {% endif %}
        </button>
    </form>

{% endblock %}

proyecto_django/bienvenido/templates/bienvenido/empleado/search_empleados.html
{% extends "base.html" %}

{%block titulo%}
    Lista Empleados
{% endblock %}

{% block contenido %}

    <form method="GET">
        <input type="text" name="nombre_empleado" value="{{ param_nombre }}">
        <button type="submit">filtar</button>    
    </form>

    {% for empleado in empleados %}
        Nombre: {{ empleado.nombre }}<br>
        Sueldo: {{ empleado.sueldo }}<br>
        {% if empleado.sueldo > 18000 %}
            Sueldo mayor a 18000 <br>
        {% endif %}
        <a href="{% url 'empleado' empleado.id %}">ver detalles</a><br>  
        <a href="{%url 'borrar_empleado' empleado.id%}">Borrar</a>
        <br>
        <br>
    {% endfor %}
{% endblock %}

proyecto_django/bienvenido/templates/bienvenido/hola.html
HOLA MUNDO! desde hola.html<br>

{{ saludo }}<br>
{{ numero }}

proyecto_django/bienvenido/templates/bienvenido/index.html
HOLA MUNDO! desde hola.html<br>

{{ saludo }}<br>
{{ numero }}

proyecto_django/bienvenido/templates/empleados.html
{% extends "base.html" %}

{%block titulo%}
    Lista Empleados
{% endblock %}

{% block contenido %}
    {% for empleado in empleados %}
        Nombre: {{ empleado.nombre }}<br>
        Sueldo: {{ empleado.sueldo }}<br>
        {% if empleado.sueldo > 18000 %}
            Sueldo mayor a 18000 <br>
        {% endif %}
        <a href="{% url 'empleado' empleado.id %}">ver detalles</a><br>  
        <a href="{%url 'borrar_empleado' empleado.id%}">Borrar</a>
        <br>
        <br>
    {% endfor %}
{% endblock %}

proyecto_django/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <title></title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>

{% include "navbar.html" %}<br>
__________________
<br><br>
{%block titulo%}
{% endblock %}
<br><br>
--------------
<br><br>

{% block contenido %}
{% endblock %}

<br><br>
----------------



</body>
</html>

proyecto_django/templates/navbar.html
<a href="{% url 'lista_empleados' %}"> Empleados </a>
<a href="{% url 'lista_departamentos' %}"> Departamentos </a>